<a href="https://colab.research.google.com/github/Usharani04/value-added-course/blob/main/arrayoprators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
b=np.random.random((3,3))

In [3]:
c=np.random.random((3,3))

In [4]:
b

array([[0.5894599 , 0.35402175, 0.75374781],
       [0.84555088, 0.08080284, 0.78170755],
       [0.17670211, 0.00933205, 0.95444603]])

In [5]:
c

array([[0.13778684, 0.42723381, 0.28504738],
       [0.61833531, 0.82159138, 0.49074826],
       [0.99114911, 0.10358076, 0.15589815]])

In [6]:
b + c

array([[0.72724674, 0.78125557, 1.03879519],
       [1.4638862 , 0.90239421, 1.27245581],
       [1.16785122, 0.11291281, 1.11034418]])

In [7]:
b -c

array([[ 0.45167306, -0.07321206,  0.46870043],
       [ 0.22721557, -0.74078854,  0.29095929],
       [-0.81444699, -0.0942487 ,  0.79854789]])

In [8]:
b*c

array([[0.08121982, 0.15125006, 0.21485384],
       [0.52283397, 0.06638692, 0.38362162],
       [0.17513814, 0.00096662, 0.14879637]])

In [9]:
b/c

array([[4.27805668, 0.82863702, 2.64428954],
       [1.36746336, 0.09834918, 1.59288909],
       [0.17828005, 0.09009446, 6.12224108]])

In [10]:
b%c

array([[0.03831255, 0.35402175, 0.18365305],
       [0.22721557, 0.08080284, 0.29095929],
       [0.17670211, 0.00933205, 0.01905716]])

In [11]:
1/c

array([[7.2575873 , 2.34063871, 3.5081887 ],
       [1.61724549, 1.21715007, 2.03770462],
       [1.00892993, 9.65430293, 6.41444446]])

In [12]:
2/b

array([[  3.39293648,   5.64937038,   2.65340738],
       [  2.36532187,  24.75160563,   2.55850158],
       [ 11.31848383, 214.3151208 ,   2.09545635]])

In [13]:
b += c #b=b+c

In [14]:
b

array([[0.72724674, 0.78125557, 1.03879519],
       [1.4638862 , 0.90239421, 1.27245581],
       [1.16785122, 0.11291281, 1.11034418]])

In [15]:
 b**2

array([[0.52888782, 0.61036026, 1.07909544],
       [2.1429628 , 0.81431532, 1.61914379],
       [1.36387647, 0.0127493 , 1.2328642 ]])

In [16]:
0.52522541 *0.52522541

0.2758617313096681

In [17]:
1.45346678 * 1.45346678

2.1125656805635686