<a href="https://colab.research.google.com/github/Usharani04/value-added-course/blob/main/Array%20Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.random.randint(12)

11

In [2]:
arr1=np.random.randn(12)

In [5]:
arr1

array([ 0.60214495, -0.17102284,  0.91867879, -0.75622487, -2.69991797,
       -0.50011698, -1.03056425, -0.73908356, -1.78743817, -0.38956518,
       -1.53310159,  0.01835532])

In [4]:
np.sqrt(arr1)

<ipython-input-4-31bdbbe4b4c3>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([0.77597999,        nan, 0.95847733,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan, 0.1354818 ])

In [6]:
np.exp(arr1)

array([1.82603134, 0.84280232, 2.50597727, 0.46943526, 0.06721103,
       0.60645971, 0.35680557, 0.47755136, 0.16738844, 0.67735134,
       0.2158651 , 1.01852481])

In [7]:
arr2=np.random.randn(12)

In [8]:
arr2

array([-0.27465453, -0.80866136, -0.39212182, -0.05911829, -0.86082085,
        0.3857281 ,  0.37685073,  0.6294992 , -0.21860714,  0.07099113,
       -0.96890853,  0.71810885])

In [9]:
np.add(arr1,arr2)

array([ 0.32749041, -0.9796842 ,  0.52655697, -0.81534316, -3.56073882,
       -0.11438888, -0.65371353, -0.10958436, -2.0060453 , -0.31857405,
       -2.50201013,  0.73646417])

In [10]:
np.minimum(arr1,arr2)

array([-0.27465453, -0.80866136, -0.39212182, -0.75622487, -2.69991797,
       -0.50011698, -1.03056425, -0.73908356, -1.78743817, -0.38956518,
       -1.53310159,  0.01835532])

In [11]:
np.maximum(arr1,arr2)

array([ 0.60214495, -0.17102284,  0.91867879, -0.05911829, -0.86082085,
        0.3857281 ,  0.37685073,  0.6294992 , -0.21860714,  0.07099113,
       -0.96890853,  0.71810885])