<a href="https://colab.research.google.com/github/Usharani04/value-added-course/blob/main/Array%20Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[ 0.11762709,  0.44547497,  0.28554453, -2.56200449],
       [ 1.09609301,  0.2109399 , -0.97056578,  0.12051475],
       [ 0.96560352, -1.76677046, -0.48186227, -1.25381744],
       [ 0.60262334,  0.90575243, -0.36172483,  0.57970256]])

In [4]:
arr.sum()

-2.0668691637195398

In [5]:
arr.mean()

-0.12917932273247124

In [8]:
arr.var()

1.0188554326319978

In [6]:
arr.std()

1.009383689501667

In [7]:
np.where(arr<0)


(array([0, 1, 2, 2, 2, 3]), array([3, 2, 1, 2, 3, 2]))

In [9]:
np.where(arr<0,0,arr)

array([[0.11762709, 0.44547497, 0.28554453, 0.        ],
       [1.09609301, 0.2109399 , 0.        , 0.12051475],
       [0.96560352, 0.        , 0.        , 0.        ],
       [0.60262334, 0.90575243, 0.        , 0.57970256]])

In [10]:
arr.sort()

In [11]:
arr

array([[-2.56200449,  0.11762709,  0.28554453,  0.44547497],
       [-0.97056578,  0.12051475,  0.2109399 ,  1.09609301],
       [-1.76677046, -1.25381744, -0.48186227,  0.96560352],
       [-0.36172483,  0.57970256,  0.60262334,  0.90575243]])